wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.0
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682572412.47529
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 13
      - 16
      - 19
      - 23
      4: 3.8.5
      5: 0.15.0
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 256
num_pretrain_rows:
  desc: null
  value: 1000000
