wandb_version: 1

_items:
  desc: null
  value:
    _wandb: {}
    batch_size: 256
    num_pretrain_rows: 1000000
_locked:
  desc: null
  value: {}
_users:
  desc: null
  value: {}
_users_inv:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_settings:
  desc: null
  value: '<Settings {''_args'': None, ''_async_upload_concurrency_limit'': None, ''_cli_only_mode'':
    None, ''_colab'': False, ''_config_dict'': None, ''_console'': <SettingsConsole.WRAP:
    1>, ''_cuda'': None, ''_disable_meta'': None, ''_disable_service'': False, ''_disable_stats'':
    None, ''_disable_viewer'': None, ''_except_exit'': None, ''_executable'': ''/global/home/users/mfong/anaconda3/bin/python'',
    ''_extra_http_headers'': None, ''_flow_control_custom'': False, ''_flow_control_disabled'':
    False, ''_internal_check_process'': 8, ''_internal_queue_timeout'': 2, ''_jupyter'':
    True, ''_jupyter_name'': ''pretrain_MLP.ipynb'', ''_jupyter_path'': ''pretrain_MLP.ipynb'',
    ''_jupyter_root'': ''/global/home/users/mfong/git/transfer-learning'', ''_kaggle'':
    False, ''_live_policy_rate_limit'': None, ''_live_policy_wait_time'': None, ''_log_level'':
    None, ''_network_buffer'': None, ''_noop'': False, ''_offline'': False, ''_sync'':
    False, ''_os'': ''Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.10'', ''_platform'':
    ''linux'', ''_python'': ''3.8.5'', ''_runqueue_item_id'': None, ''_save_requirements'':
    True, ''_service_transport'': None, ''_service_wait'': 30.0, ''_start_datetime'':
    datetime.datetime(2023, 4, 26, 22, 13, 32, 459727), ''_start_time'': 1682572412.459727,
    ''_stats_pid'': 32384, ''_stats_sample_rate_seconds'': 2.0, ''_stats_samples_to_average'':
    15, ''_stats_join_assets'': True, ''_stats_neuron_monitor_config_path'': None,
    ''_stats_open_metrics_endpoints'': None, ''_stats_open_metrics_filters'': {''.*'':
    {}}, ''_tmp_code_dir'': ''/global/home/users/mfong/git/transfer-learning/wandb/run-20230426_221332-9193a0mq/tmp/code'',
    ''_tracelog'': None, ''_unsaved_keys'': None, ''_windows'': False, ''allow_val_change'':
    None, ''anonymous'': None, ''api_key'': ''***REDACTED***'', ''base_url'': ''https://api.wandb.ai'',
    ''code_dir'': None, ''config_paths'': None, ''console'': ''auto'', ''deployment'':
    ''cloud'', ''disable_code'': None, ''disable_git'': False, ''disable_hints'':
    None, ''disable_job_creation'': False, ''disabled'': False, ''docker'': None,
    ''email'': ''mingfong07@hotmail.com'', ''entity'': ''mingfong'', ''files_dir'':
    ''/global/home/users/mfong/git/transfer-learning/wandb/run-20230426_221332-9193a0mq/files'',
    ''force'': None, ''git_commit'': ''e02095a6b83d191cb5982bf0c3a20768b9b26fff'',
    ''git_remote'': ''origin'', ''git_remote_url'': ''https://github.com/evilpegasus/transfer-learning.git'',
    ''git_root'': None, ''heartbeat_seconds'': 30, ''host'': ''ml4hep2'', ''ignore_globs'':
    (), ''init_timeout'': 60.0, ''is_local'': False, ''label_disable'': None, ''launch'':
    None, ''launch_config_path'': None, ''log_dir'': ''/global/home/users/mfong/git/transfer-learning/wandb/run-20230426_221332-9193a0mq/logs'',
    ''log_internal'': ''/global/home/users/mfong/git/transfer-learning/wandb/run-20230426_221332-9193a0mq/logs/debug-internal.log'',
    ''log_symlink_internal'': ''/global/home/users/mfong/git/transfer-learning/wandb/debug-internal.log'',
    ''log_symlink_user'': ''/global/home/users/mfong/git/transfer-learning/wandb/debug.log'',
    ''log_user'': ''/global/home/users/mfong/git/transfer-learning/wandb/run-20230426_221332-9193a0mq/logs/debug.log'',
    ''login_timeout'': None, ''magic'': None, ''mode'': ''online'', ''notebook_name'':
    ''pretrain_MLP.ipynb'', ''problem'': ''fatal'', ''program'': ''<python with no
    main file>'', ''program_relpath'': None, ''project'': ''pretrain_MLP'', ''project_url'':
    ''https://wandb.ai/mingfong/pretrain_MLP'', ''quiet'': None, ''reinit'': None,
    ''relogin'': None, ''resume'': None, ''resume_fname'': ''/global/home/users/mfong/git/transfer-learning/wandb/wandb-resume.json'',
    ''resumed'': False, ''root_dir'': ''/global/home/users/mfong/git/transfer-learning'',
    ''run_group'': None, ''run_id'': ''9193a0mq'', ''run_job_type'': None, ''run_mode'':
    ''run'', ''run_name'': ''pretrain_MLP'', ''run_notes'': None, ''run_tags'': None,
    ''run_url'': ''https://wandb.ai/mingfong/pretrain_MLP/runs/9193a0mq'', ''sagemaker_disable'':
    None, ''save_code'': None, ''settings_system'': ''/global/home/users/mfong/.config/wandb/settings'',
    ''settings_workspace'': ''/global/home/users/mfong/git/transfer-learning/wandb/settings'',
    ''show_colors'': None, ''show_emoji'': None, ''show_errors'': True, ''show_info'':
    True, ''show_warnings'': True, ''silent'': False, ''start_method'': None, ''strict'':
    None, ''summary_errors'': None, ''summary_timeout'': 60, ''summary_warnings'':
    5, ''sweep_id'': None, ''sweep_param_path'': None, ''sweep_url'': '''', ''symlink'':
    True, ''sync_dir'': ''/global/home/users/mfong/git/transfer-learning/wandb/run-20230426_221332-9193a0mq'',
    ''sync_file'': ''/global/home/users/mfong/git/transfer-learning/wandb/run-20230426_221332-9193a0mq/run-9193a0mq.wandb'',
    ''sync_symlink_latest'': ''/global/home/users/mfong/git/transfer-learning/wandb/latest-run'',
    ''system_sample'': 15, ''system_sample_seconds'': 2, ''table_raise_on_max_row_limit_exceeded'':
    False, ''timespec'': ''20230426_221332'', ''tmp_dir'': ''/global/home/users/mfong/git/transfer-learning/wandb/run-20230426_221332-9193a0mq/tmp'',
    ''username'': ''mfong'', ''wandb_dir'': ''/global/home/users/mfong/git/transfer-learning/wandb/''}>'
_artifact_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_artifact_callback
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.0
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682582535.162405
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 13
      - 16
      - 19
      - 23
      4: 3.8.5
      5: 0.15.0
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 256
num_pretrain_rows:
  desc: null
  value: 1000000
